ERROR:app:Exception on /query/new [POST]
Traceback (most recent call last):
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/datadrive/qgv1/text_prod/app.py", line 600, in new
    mcq(myqg, results, payload)
  File "/datadrive/qgv1/text_prod/app.py", line 82, in mcq
    output = qg.predict_mcq(
  File "/datadrive/qgv1/text_prod/BalaQGFile.py", line 116, in predict_mcq
    coref_text = improved_replace_corefs(self.nlp(context), self.predictor.predict(context)['clusters'])
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp_models/coref/predictors/coref.py", line 64, in predict
    return self.predict_json({"document": document})
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 55, in predict_json
    return self.predict_instance(instance)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 263, in predict_instance
    outputs = self._model.forward_on_instance(instance)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/models/model.py", line 172, in forward_on_instance
    return self.forward_on_instances([instance])[0]
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/models/model.py", line 198, in forward_on_instances
    outputs = self.make_output_human_readable(self(**model_input))
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp_models/coref/models/coref.py", line 221, in forward
    top_span_mention_scores, top_span_mask, top_span_indices = util.masked_topk(
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/nn/util.py", line 1997, in masked_topk
    raise ValueError("`input_` and `mask` must have the same shape.")
ValueError: `input_` and `mask` must have the same shape.
ERROR:app:Exception on /query/new [POST]
Traceback (most recent call last):
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/datadrive/qgv1/text_prod/app.py", line 601, in new
    mcq(myqg, results, payload)
  File "/datadrive/qgv1/text_prod/app.py", line 82, in mcq
    output = qg.predict_mcq(
  File "/datadrive/qgv1/text_prod/BalaQGFile.py", line 116, in predict_mcq
    coref_text = improved_replace_corefs(self.nlp(context), self.predictor.predict(context)['clusters'])
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp_models/coref/predictors/coref.py", line 64, in predict
    return self.predict_json({"document": document})
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 55, in predict_json
    return self.predict_instance(instance)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 263, in predict_instance
    outputs = self._model.forward_on_instance(instance)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/models/model.py", line 172, in forward_on_instance
    return self.forward_on_instances([instance])[0]
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/models/model.py", line 198, in forward_on_instances
    outputs = self.make_output_human_readable(self(**model_input))
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp_models/coref/models/coref.py", line 221, in forward
    top_span_mention_scores, top_span_mask, top_span_indices = util.masked_topk(
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/allennlp/nn/util.py", line 2049, in masked_topk
    fill_value, _ = top_indices.max(dim=1, keepdim=True)
IndexError: max(): Expected reduction dim 1 to have non-zero size.
