  ERROR:app:Exception on /query/new [POST]
Traceback (most recent call last):
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nravulapalli/miniconda3/envs/qgv1_env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/datadrive/qgv1/text_prod/app.py", line 601, in new
    mcq(myqg, results, payload)
  File "/datadrive/qgv1/text_prod/app.py", line 82, in mcq
    output = qg.predict_mcq(
  File "/datadrive/qgv1/text_prod/BalaQGFile.py", line 107, in predict_mcq
    logging.error('filtering ' + datetime.datetime.now()-beginFilter)
TypeError: can only concatenate str (not "datetime.datetime") to str
ERROR:root:filtering 0:00:01.336174
ERROR:root:coref 0:00:11.648345
ERROR:root:aExtraction 0:00:01.623518
ERROR:root:QG 0:00:07.192641
ERROR:root:Distractor 0:02:07.810552
ERROR:root:Request 0:00:10.098004
